baseURL = 'https://safesh.xyz/'
languageCode = 'en-us'
title = 'safesh'
theme = 'PaperMod'

# For hugo >= 0.60.0, enable inline HTML
[markup.goldmark.renderer]
unsafe = true

[params.profileMode]
enabled = true
title = "safesh"
subtitle = "Fast, safe, and easy to use SSH key infrastructure."
imageUrl = "safesh.png"
imageWidth = 120
imageHeight = 120

[[params.socialIcons]]
name = "github"
url = "https://github.com/safesh"

[minify]
disableXML = true
